### PR TITLE
Fix QoS2 message retry

### LINKED ISSUE #43: Resend PUBREL
MQTT-4.4.0-1

### LINKED ISSUE #152: Fix QoS2 message publish retry
QoS2 message arrives twice by ReconnectClient. (tested by #151)

### PR DESCRIPTION
**Pull request by at-wat**
fix #152 
fix #43

### CODE REVIEW

File: error.go [hunk 1]
```diff
@@ -15,13 +15,38 @@
...
 	"io"
 	"path/filepath"
 	"reflect"
 	"runtime"
 )
 
+// ErrorWithRetry is a error with packets which should be retransmitted.
+type ErrorWithRetry interface {
+	error
+	retry(context.Context, *BaseClient) error
```
Comment (at-wat) [inline error.go:29]: Can be public.
